### ISSUE TITLE
npm install doesn't pull in all the files

### ISSUE THREAD

**Issue by timwis** [bendrucker/document-ready#2]
Hi @bendrucker, both @yoshuawuyts and I have experienced a problem where doing `npm install` on this repo only pulls in a few files (`license`, `package.json`, and `readme.md`). Personally, this occurred when I was doing `npm install yoshuawuyts/choo#3.0` which lists `document-ready~1.0.1` as a dependency. I believe Yosh is pinging npm, but wanted to make you aware as well.

**Comment by yoshuawuyts** [comment]
Just asked in IRC - no response yet. Perhaps quickest fix is to publish a patch version and valide the output; reckon if it's a cache issue that might fix it. Thanks! :sparkles:

**Comment by timwis** [comment]
@yoshuawuyts we can also make choo use `bendrucker/document-ready#commit-hash` as the dep to avoid npmjs cache probably

**Comment by bendrucker** [comment]
It's node 6, not caching. I think I'd accidentally left `n` on v6 after testing something. v6 still has severe `npm publish` bugs AFAIK. Just deprecated 1.0.1 and published 1.0.2.
