### ISSUE TITLE
Doesn't fire when loaded from async script

### ISSUE THREAD

**Issue by paul-veevers** [bendrucker/document-ready#3]
The callback isn't called when the script is loaded async; i.e. `<script src="index.js" async="true"></script>`

See here for a repro: https://gist.github.com/paul-veevers/01081a1b929fa7f55ceeb97c0046195f

Same issue here: https://github.com/ded/domready/issues/38
And fixed by: https://github.com/ded/domready/pull/32

Need this fixed as I'm using Choo :) cc @yoshuawuyts 

Happy to do a PR if that will help.

**Comment by yoshuawuyts** [comment]
PR def welcome!

**Comment by bendrucker** [comment]
Thanks! Wasn't sure why the linked repo went with a regex instead of explicit matching so I stuck with the simpler route.

**Comment by yoshuawuyts** [comment]
raddd!

**Comment by paul-veevers** [comment]
Thank you!
