### ISSUE TITLE
why this module uses assert? 

### ISSUE THREAD

**Issue by bboydflo** [bendrucker/document-ready#7]
isn't assert a nodejs module. does it make sense to use it for this browser module?

**Comment by bendrucker** [comment]
It is! Depending on how you think about it, `module.exports` implies a Node.js module. Technically CommonJS, but most browser bundlers handle them as node modules and include special browser versions. So this repo is document-ready as a Node-style module, but for the browser.

Check out [unassert](https://github.com/unassert-js/unassert), it can compile all the asserts out of your app.

I'd also consider a PR replacing the assertion with an if/throw to minimize default bundled size.
